version: '2'

services:
  app:
    container_name: planwise-prod-app
    image: instedd/planwise:latest
    environment:
      CALCULATE_DEMAND: 'true'
      DATABASE_URL: "jdbc:postgresql://db/planwise?user=planwise&password=planwise"
      MAIL_SENDER: planwise-test@instedd.org
      PORT: 3000
      POSTGRES_DB: planwise
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: planwise
      POSTGRES_USER: planwise
      RASTER_ISOCHRONES: 'true'
    env_file: ".docker-env"
    volumes:
      - data:/data
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    container_name: planwise-prod-db
    image: starefossen/pgrouting:10.1-2.4-2.5
    environment:
      POSTGRES_PASSWORD: planwise
      POSTGRES_USER: planwise
      POSTGRES_DB: routing
    volumes:
      - db:/var/lib/postgresql/data

  mapcache:
    container_name: planwise-prod-mapcache
    image: instedd/planwise-mapcache:kenya
    pid: host

  mapserver:
    container_name: planwise-prod-mapserver
    image: instedd/planwise-mapserver:kenya
    pid: host
    volumes:
      - data:/data

volumes:
  db:
  data:
