version: '2'

services:
  db:
    image: starefossen/pgrouting:10.1-2.4-2.5
    environment:
      POSTGRES_PASSWORD: planwise
      POSTGRES_USER: planwise
      POSTGRES_DB: planwise
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  mapcache:
    image: instedd/planwise-mapserver:mapcache
    # build: .
    # dockerfile: Dockerfile.mapcache
    volumes:
      - "./mapserver/mapcache.xml:/mapcache/mapcache.xml:ro"
    links:
      - mapserver
    ports:
      - "5002:80"

  mapserver:
    image: instedd/planwise-mapserver:mapserver
    # build: .
    # dockerfile: Dockerfile.mapserver
    volumes:
      - "./data:/data:ro"
      - "./mapserver/planwise.map:/etc/mapserver/mapserver.map:ro"
    ports:
      - "5001:80"

volumes:
  db:
