version: '2'

services:
  app:
    image: instedd/planwise:latest
    environment:
      DATA_PATH: /app/data
      DATABASE_URL: "jdbc:postgresql://db/routing?user=planwise&password=planwise"
      POSTGRES_PASSWORD: planwise
      POSTGRES_USER: planwise
      POSTGRES_DB: routing
      POSTGRES_HOST: db
      PORT: 3000
      CALCULATE_DEMAND: 'false'
      RASTER_ISOCHRONES: 'false'
    env_file: ".docker-env"

  db:
    image: starefossen/pgrouting:9.4-2.1-2.1
    environment:
      POSTGRES_PASSWORD: planwise
      POSTGRES_USER: planwise
      POSTGRES_DB: routing
    volumes:
      - db:/var/lib/postgresql/data
