FROM clojure:lein-2.8.1

RUN echo 'deb http://archive.debian.org/debian stretch main\n\
          deb http://archive.debian.org/debian-security stretch/updates main' > /etc/apt/sources.list

RUN apt update && \
    apt install -y build-essential cmake \
                   libboost-timer-dev libboost-program-options-dev \
                   libboost-filesystem-dev \
                   libpq-dev libgdal-dev postgresql-client libpq-dev \
                   gdal-bin python-gdal libgdal-java \
                   && \
    curl -sL https://deb.nodesource.com/setup_9.x | bash - && \
    apt-get install -y nodejs

WORKDIR /app
