FROM clojure:lein-2.8.1

RUN apt update && \
    apt install -y build-essential libboost-program-options-dev libpq-dev \
                   libgdal-dev postgresql-client libpq-dev gdal-bin python-gdal libgdal-java \
                   osm2pgrouting

WORKDIR /app

