version: '2'

services:
  app:
    build:
      dockerfile: Dockerfile-dev
      context: .
    volumes:
      - ".:/app"
      - m2:/root/.m2
      - "~/.lein:/root/.lein"
    links:
      - db
    env_file:
      - ./docker-env
    command: "lein repl :headless"
    ports:
      - "47480:47480"
      - "3000:3000"

  client:
    build:
      dockerfile: Dockerfile-dev
      context: .
    volumes:
      - ".:/app"
      - m2:/root/.m2
      - node_modules:/app/client/node_modules
    working_dir: "/app/client"
    command: "sh -c 'npm install && npm run watch'"
    ports:
      - "9630:9630"

  db:
    image: starefossen/pgrouting:10.1-2.4-2.5
    environment:
      POSTGRES_PASSWORD: planwise
      POSTGRES_USER: planwise
      POSTGRES_DB: planwise
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  mapcache:
    image: camptocamp/mapcache:1.4
    volumes:
      - "./mapserver/mapcache.xml:/mapcache/mapcache.xml:ro"
    links:
      - mapserver
    ports:
      - "5002:80"

  mapserver:
    image: camptocamp/mapserver:7.0
    volumes:
      - "./data:/data:ro"
      - "./mapserver/planwise.map:/etc/mapserver/planwise.map:ro"
    ports:
      - "5001:80"

  tools:
    build:
      context: scripts/tools
    env_file:
      - ./docker-env
    volumes:
      - "./data:/data"
    links:
      - db

volumes:
  db:
  m2:
  node_modules:
