[package]
name = "walking-coverage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "=4.4.17", features = ["derive"] }
thiserror = "1.0.58"
gdal.workspace = true
