#!/bin/bash
set -euo pipefail

if [[ ! -e kenya-facilities.json ]]; then
  echo "Downloading Kenya sites"
  curl -XGET https://s3.amazonaws.com/planwise/data/kenya-facilities-20160627.json > kenya-facilities.json
fi

echo "Importing Kenya sites"
if [[ -x $(command -v lein) ]]; then
  lein import-sites `pwd`/kenya-facilities.json
elif [[ -e $JAR_PATH ]]; then
  java -cp $JAR_PATH planwise.tasks.import_sites `pwd`/kenya-facilities.json
else
  echo "Not jar path '$JAR_PATH' nor lein command were found. Aborting."
fi
