#! /bin/bash
set -euo pipefail

# Returns the population under an isochrone

# Used in facilities.clj

# FIXME: adapt for normalized population rasters if necessary

if [ $# -lt 2 ]; then
  echo "Usage: $0 FACILITY_POLYGON_ID | $1 COUNTRY"
	exit 1
fi

DATA_PATH=${DATA_PATH:-data}
BIN_PATH=${BIN_PATH:-cpp}
TMP_PATH=${TMP_PATH:-/tmp}
FACILITY_POLYGON_ID=$1

if   [[ $2 == "kenya" ]];        then POPULATION_FILE=${DATA_PATH}/KEN_popmap15_v2b.tif
elif [[ $2 == "tanzania" ]];     then POPULATION_FILE=${DATA_PATH}/TZA_popmap15_v2b.tif
elif [[ $2 == "ethiopia" ]];     then POPULATION_FILE=${DATA_PATH}/ETH15v5.tif
elif [[ $2 == "nigeria" ]];      then POPULATION_FILE=${DATA_PATH}/NGA14adjv1.tif
elif [[ $2 == "south-africa" ]]; then POPULATION_FILE=${DATA_PATH}/ZAF15v4.tif
elif [[ $2 == "niger" ]];        then POPULATION_FILE=${DATA_PATH}/NER15adjv4.tif
elif [[ $2 == "uganda" ]];       then POPULATION_FILE=${DATA_PATH}/UGA_ppp_v2b_2015_UNadj.tif
else
    echo "ERROR: Unknown country: $2"
    exit 1
fi

if [[ ! -e $POPULATION_FILE ]]; then
    echo "ERROR: Region population raster ${POPULATION_FILE} not found";
    exit 1;
fi;

VRT_TARGET=${TMP_PATH}/${FACILITY_POLYGON_ID}.vrt
gdalwarp -q \
  -co "TILED=YES" -co "BLOCKXSIZE=128" -co "BLOCKYSIZE=128" \
  -cutline PG:"dbname=${POSTGRES_DB} host=${POSTGRES_HOST} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD}" \
  -csql "SELECT the_geom FROM facilities_polygons WHERE id = ${FACILITY_POLYGON_ID};" \
  -crop_to_cutline \
  -of VRT \
  $POPULATION_FILE $VRT_TARGET

IFS=' ' read -a AGGREGATES <<< $(${BIN_PATH}/aggregate-population ${VRT_TARGET})
echo ${AGGREGATES[0]}
rm ${VRT_TARGET}
