#! /bin/bash
set -euo pipefail

# Creates byte-sized raster files data/isochrones/REGIONID/FACILITY_POLYGON_ID.tif,
# with a 255 value for each facility polygon, intersected with the specified REGION,
# with the same size and extent as the REGION raster

function query {
  psql -d $POSTGRES_DB -U $POSTGRES_USER -h $POSTGRES_HOST -t -A -c "$1";
}

echo "Rasterizing isochrones per region"
mkdir -p data/isochrones/
REGION_IDS="$(query 'SELECT id FROM regions ORDER BY id;')"

for regionid in $REGION_IDS; do
  echo "Region ${regionid}"

  QUERY="WITH region AS (SELECT regions.the_geom AS region_geom FROM regions WHERE regions.id = ${regionid})
  SELECT facilities_polygons.id
  FROM facilities INNER JOIN facilities_polygons
  ON facilities.id = facilities_polygons.facility_id
  WHERE ST_Intersects(facilities_polygons.the_geom, (SELECT region.region_geom FROM region))
  ORDER BY facilities_polygons.id;"

  FACILITY_POLYGON_IDS="$(query "$QUERY")"

  for id in $FACILITY_POLYGON_IDS; do
    echo "Processing polygon ${id}"
    $(dirname "${BASH_SOURCE}")/raster-isochrone ${regionid} ${id}
  done;

done;
