#! /bin/bash
set -euo pipefail

# Creates byte-sized raster files data/isochrones/REGIONID/FACILITY_POLYGON_ID.tif,
# with a 255 value for each facility polygon, intersected with the specified REGION,
# with the same size and extent as the REGION raster

# To be invoked to setup all isochrones or for a specific facility
# Note that this should not be necessary on a freshly imported facilities dataset,
# as the import process already invokes raster-isochrone for each isochrone

function query {
  psql -d $POSTGRES_DB -U $POSTGRES_USER -h $POSTGRES_HOST -t -A -c "$1";
}

echo "Rasterizing isochrones per region"
mkdir -p data/isochrones/
REGION_IDS="$(query 'SELECT id FROM regions ORDER BY id;')"
SCRIPTS_DIR=$(dirname "${BASH_SOURCE}")

if [ $# -lt 1 ]; then
  FACILITY_CONDITION=""
else
  echo "Filtering by facility $1"
  FACILITY_CONDITION="AND facilities_polygons.facility_id = '$1'"
fi;

for regionid in $REGION_IDS; do
  echo "Region ${regionid}"

  QUERY="WITH region AS (SELECT regions.the_geom AS region_geom FROM regions WHERE regions.id = ${regionid})
  SELECT facilities_polygons.id
  FROM facilities_polygons
  WHERE ST_Intersects(facilities_polygons.the_geom, (SELECT region.region_geom FROM region))
        ${FACILITY_CONDITION}
  ORDER BY facilities_polygons.id;"

  FACILITY_POLYGON_IDS="$(query "$QUERY")"

  for id in $FACILITY_POLYGON_IDS; do
    echo "Processing polygon ${id}"
    POPULATION=$(${SCRIPTS_DIR}/raster-isochrone ${regionid} ${id})
    query "UPDATE facilities_polygons_regions SET population = ${POPULATION} WHERE facility_polygon_id = ${id} AND region_id = ${regionid};"
  done;

done;
